version: "3"
services:
  backend:
    container_name: instagram_backend
    build: . # Build the image from the Dockerfile in the current directory
    ports:
      - "8080:8080" # Map port 8080 of the container to port 8080 on the host
    env_file:
      - .env # Load environment variables from the .env file
    environment:
      - PORT=8080 # This overrides the value in the .env file if present
    restart: always # Restart the container automatically if it stops
