version: "3"
services:
  backend:
    container_name: taxi_management_backend
    build: . # Build the image from the Dockerfile in the current directory
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: always
